Cover image for Como adicionar o Snake Game (jogo da cobrinha) no seu perfil do Github ðŸ
Henrique Lopes
Henrique Lopes
Posted on 4 de jan. de 2022

 5  3  
Como adicionar o Snake Game (jogo da cobrinha) no seu perfil do Github ðŸ
#
github
Primeiramente devo deixar claro que esse artigo foi desenvolvido com base em vÃ¡rios outros artigos e reconstruÃ­do para deixar o mais claro possÃ­vel a forma para inserir o Snake Game em seu perfil.

Funcionamento. "Contributions in the last year":
Basicamente o Snake game funciona realizando uma coleta da sua tabela de contribuiÃ§Ãµes no Github. ele faz a renderizaÃ§Ã£o dessas informaÃ§Ãµes e gera dois arquivos, um em formato gif e outro em svg. SÃ£o esses arquivos que iremos utilizar para inserir a animaÃ§Ã£o no perfil do Github.

Repositorio do projeto a ser utilizado: Platane/snk

Exemple

Requisito. "RepositÃ³rio base":
Para que vocÃª possa prosseguir Ã© necessÃ¡rio que vocÃª tenha o repositÃ³rio do perfil (repositÃ³rio com o mesmo nome de usuÃ¡rio), porÃ©m para gerar os arquivos tambÃ©m funciona em outro repositÃ³rio.

Actions. "ConfiguraÃ§Ã£o inicial":
Inicialmente Ã© necessÃ¡rio que vocÃª acesse o seu repositÃ³rio escolhido e vÃ¡ em Settings.

ConfiguraÃ§Ã£o inicial

No menu vertical ao lado esquerdo selecione o menu Actions e em seguida ative a permissÃ£o â€œAllow all actionsâ€. TambÃ©m Ã© possÃ­vel selecionar diretamente o repositÃ³rio.

Ative a permissÃ£o

Actions. "Criando Gerador":
Agora que temos o repositÃ³rio configurado iremos adicionar o "script" para gerar dos arquivos. No repositÃ³rio, vÃ¡ em Actions.

Criando o gerador

Em seguida vamos utilizar â€œSimple workflowâ€ apenas com o mÃ­nimo necessÃ¡rio para rodar o codigo.

Configurando

Agora Ã© apenas alterar o nome do arquivo e colar o cÃ³digo da configuraÃ§Ã£o com o seu usuÃ¡rio.

Alterar jnome do arquivo

alterando o username
# Nome da Actions:  
name: Snake Game

# Controlador do tempo que sera feito a atualizaÃ§Ã£o dos arquivos.
on:
  schedule:
      # SerÃ¡ atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Repositorio que serÃ¡ utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: nomeUsuario #Seu usuario
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizaÃ§Ãµes.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Retornando na opÃ§Ã£o Actions do repositÃ³rio, clique em â€œRun workflowâ€:

Repositorio

Pasta dos arquivos:
Em seu repositorio cliente em main e selecione a branch output:
output

E aqui estÃ£o os arquivos gerados que vocÃª pode utilizar como bem entender:

Arquivos

Codigo Github para utilizaÃ§Ã£o:

![snake gif](https://github.com/SEU_USUARIO/SEU_REPOSITORIO/blob/output/github-contribution-grid-snake.svg)

Top comments (0)

Subscribe
pic
Add to the discussion
Code of Conduct â€¢ Report abuse
DEV Community

5 Websites To Learn Frontend Web Development Faster ðŸ’¨


>> Check out this classic DEV post <<

Read next
c4r4x35 profile image
Options Pattern in Golang
Srinivas Kandukuri - Dec 13 '22

gioboa profile image
VSCode & GitHub Codespaces for my Python playground
Giorgio Boa - Dec 10 '22

techielass profile image
Deploying Azure Bicep using GitHub Actions
Sarah Lean ðŸ´ó §ó ¢ - Dec 1 '22

andreasaugustin profile image
Git - GitHub actions-template-sync
Andreas Augustin - Dec 11 '22


Henrique Lopes
Follow
"NÃ£o hÃ¡ razÃ£o alguma em usar a palavra â€œimpossÃ­velâ€ para descrever algo que claramente pode acontecer."
JOINED
5 de set. de 2021
Trending on DEV Community 
Dima Sukharev profile image
Use AI to commit like a PRO in 1 second
#git #tutorial #productivity #ai
Medea profile image
Best way to learn a framework/language
#beginners #programming #codenewbie #discuss
vincanger profile image
10 "Hard Truths" All Junior Developers Need to Hear
#webdev #beginners #career #discuss
DEV Community

ðŸŒš Life is too short to browse without dark mode
# Nome da Actions:  
name: Snake Game

# Controlador do tempo que sera feito a atualizaÃ§Ã£o dos arquivos.
on:
  schedule:
      # SerÃ¡ atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Repositorio que serÃ¡ utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: nomeUsuario #Seu usuario
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizaÃ§Ãµes.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
